language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24
  licenses:
      - android-sdk-license-.+

before_install:
  - chmod +x gradlew
  - android update sdk --filter extra-android-support --no-ui --force > /dev/null

sudo: true